.TH "" "" "" "" ""
.SH edx\-test\-course
.RS
.PP
test solutions of course exercises against the grader
.RE
.SS Install
.PP
Install it with
.IP
.nf
\f[C]
npm\ install\ edx\-test\-course
\f[]
.fi
.SS Usage
.IP
.nf
\f[C]
Usage:
\ \ \ \ edx\-test\-course\ justone\ DIR\ ENDPOINT\ NUM\ 
\ \ \ \ edx\-test\-course\ all\ DIR\ ENDPOINT\ 
\ \ \ \ edx\-test\-course\ (\ \-h\ |\ \-\-help\ )

Options:
\ \ \ \ \-h,\ \-\-help\ \ \ \ \ \ \ \ \ \ \ \ \ \ help\ for\ edx\-test\-course
\ \ \ \ 
Commands:

Arguments:
\ \ \ \ DIR\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ directory\ of\ the\ course
\ \ \ \ ENDPOINT\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ grader\ endpoint\ address\ (IP:PORT)
\ \ \ \ NUM\ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ \ exe\ num.
\f[]
.fi
.SS Author
.IP \[bu] 2
Vittorio Zaccaria
.SS License
.PP
Released under the BSD License.
.PP
   *   *   *   *   *
.SH Bug fixes
.IP \[bu] 2
fix search path for edx converter \-\- Jul 18th
16 (../../commit/1c8a2247ef22dda292247f20182675a3b257d92b)
.IP \[bu] 2
update version of gitbook3toedx \-\- Jul 18th
16 (../../commit/d48ca3183025212997adff391200f5ad56f17ec4)
.IP \[bu] 2
clean up succesfull test output \-\- Jun 22nd
16 (../../commit/ce39a61e3319435906880b7d8cbcba48afc411b1)
